var DetailsPageJs=new Class.create;
DetailsPageJs.prototype=Object.extend(new BPCPageJs,{_item:null,_readOnlyMode:!1,_dirty:!1,_getFormGroup:function(a,c,d){var b;b=new Element("div",{"class":"form-group form-group-sm"});a&&("string"!==typeof a||"string"===typeof a&&!a.blank())&&b.insert({bottom:(new Element("label")).update(a)});b.insert({bottom:c.addClassName(!0===d?"":"form-control")});return b},refreshParentWindow:function(){var a,c,d;if(parent.window)return a=parent.window,(c=$(a.document.body).down("#"+a.pageJs.resultDivId+" .item_row[item_id="+
	this._item.id+"]"))?(c.replace(a.pageJs._getResultRow(this._item)),c.hasClassName("success")||c.addClassName("success")):$(a.document.body).down("#"+a.pageJs.resultDivId+" #item-list-body")&&($(a.document.body).down("#"+a.pageJs.resultDivId+" #item-list-body").insert({top:a.pageJs._getResultRow(this._item)}),(d=$(a.document.body).down("#"+a.pageJs.totalNoOfItemsId))&&d.update(parseInt(d.innerHTML)+1)),this},_getSaveBtn:function(){var a={me:this};a.me._refreshDirty();if(!a.me._containerIds||!a.me._containerIds.saveBtn)return a.me;
	a.container=$(a.me._containerIds.saveBtn);if(!a.container)return a.me;a.save=(new Element("i")).addClassName("btn btn-success btn-md").update("Save").observe("click",function(c){a.btn=$(this);a.data=a.me.collectData();if(!0===a.btn.readAttribute("disabled")||"disabled"===a.btn.readAttribute("disabled")||null===a.data||null===a.data)return a.me;a.me._item&&a.me._item.id&&(a.data.id=a.me._item.id);a.me.saveItem(a.input,a.data)});a.cancel=(new Element("i")).addClassName("btn btn-default btn-md").update("Cancel").observe("click",
		function(c){a.me.closeFancyBox()});a.container.update("").addClassName("col-xs-12").insert({bottom:a.me._getFormGroup(a.title,a.save).addClassName("col-xs-6")}).insert({bottom:a.me._getFormGroup(a.title,a.cancel).addClassName("pull-right col-xs-6")});!1===a.me._dirty&&a.save.hide();return a.me},collectData:function(){return this._collectFormData($(this.getHTMLID("itemDiv")),"save-item")},closeFancyBox:function(){parent.jQuery&&parent.jQuery.fancybox?parent.jQuery.fancybox.close():location.reload();
	return this},_getDatePickerDiv:function(a,c,d,b,k,n,l){var g,f,e,m,h;g=this;b=b||g.ucfirst(a);f=!0===k;l=l||"col-xs-12";n=n||"DD/MM/YYYY";d.id||g._signRandID(d);if(d=$(d.id)){e=(new Element("input")).writeAttribute({required:f,"save-item":a,dirty:!1}).setValue(c||"");d.update(g._getFormGroup(b,e).addClassName(l));if("function"!==typeof jQuery(document).datetimepicker)return g;g._signRandID(e);m=jQuery("#"+e.id).datetimepicker({format:n,showClear:!k});m.on("dp.change keyup",function(b){m.data("DateTimePicker")&&
m.data("DateTimePicker").date()?(h=m.data("DateTimePicker").date().local().format("YYYY-MM-DDThh:mm:ss"),a.endsWith("from")&&h.format("YYYY-MM-DDT00:00:00"),a.endsWith("to")&&h.format("YYYY-MM-DDT23:59:59")):h="";e.writeAttribute("dirty",c!==h);g._refreshDirty()._getSaveBtn()});return g}},__validateContainer:function(a){a=a||null;if(!a)return null;a.id||this._signRandID(a);return a.id&&0!==jQuery("#"+a.id).length?a:null},_getInputDiv:function(a,c,d,b,k,n,l,g,f){var e,m,h;e=this;d=e.__validateContainer(d);
	b=b||e.ucfirst(e.decamelize(a));k=!0===k;n=n||"col-xs-12";m=!0===l;l=g||"";f=f||"text";if(!d)return e;h=(new Element("input")).writeAttribute({required:k,"save-item":a,placeholder:""!==l?l:b,dirty:!1,type:f}).setValue(c||"").observe("change",function(a){!0===m&&h.setValue(e.getValueFromCurrency($F(h)))}).observe("keyup",function(a){h.writeAttribute("dirty",c!==(!0===m?e.getValueFromCurrency($F(h)):$F(h)));e._refreshDirty()._getSaveBtn()}).observe("click",function(a){h.writeAttribute("dirty",c!==("checkbox"===
		h.type?h.checked:!0===m?e.getValueFromCurrency($F(h)):$F(h)));e._refreshDirty()._getSaveBtn()});d.update(e._getFormGroup(b,h).addClassName(n));return e},_getSelectDiv:function(a,c,d,b,k,n,l){var g,f,e;g=this;b=g.__validateContainer(b);k=k||g.ucfirst(a);n=!0===n;l=l||"col-xs-12";if(!b)return g;f=(new Element("select")).writeAttribute({required:n,"save-item":a,dirty:!1});Array.isArray(d)&&f.writeAttribute({multiple:!0});c.each(function(a){f.insert({bottom:e=(new Element("option",{value:a.id})).update(a.name)});
	(Array.isArray(d)&&-1<d.indexOf(a.id)||a.id==d)&&e.writeAttribute("selected",!0)});f.observe("keyup",function(a){f.writeAttribute("dirty",$F(f));g._refreshDirty()._getSaveBtn()});b.update(g._getFormGroup(k,f).addClassName(l));return g},_refreshDirty:function(){var a;a=!1;$(this.getHTMLID("itemDiv")).getElementsBySelector("[save-item]").each(function(c){!1!==a||!0!==c.readAttribute("dirty")&&"true"!==c.readAttribute("dirty")&&"dirty"!==c.readAttribute("dirty")||(a=!0)});this._dirty=a;return this},
	_getSelect2Div:function(a,c,d,b,k,n,l,g){var f,e,m,h;f=this;b=f.__validateContainer(b);k=k||f.ucfirst(c);n=!0===n;l=l||null;g=g||"col-xs-12";if(!b)return f;c=(new Element("input")).writeAttribute("required",n).writeAttribute("placeholder","Please select a "+a).writeAttribute("save-item",c);b.insert({bottom:f._getFormGroup(k,c).addClassName(g)});f._signRandID(c);e=[];f._item&&f._item.id&&(Array.isArray(d)?d.each(function(a){e.push({id:a.id,text:a.name,data:a})}):e=d);m=jQuery("#"+c.id).select2(l?l:
	{multiple:!0,allowClear:!0,width:"100%",ajax:{delay:250,url:"/ajax/getAll",type:"GET",data:function(b){return{searchTxt:"name like ?",searchParams:["%"+b+"%"],entityName:a,pageNo:1}},results:function(a,b,c){h=[];a.resultData&&a.resultData.items&&a.resultData.items.each(function(a){h.push({id:a.id,text:a.name,data:a})});return{results:h}}},cache:!0,escapeMarkup:function(a){return a}});m.on("change",function(){m.attr("dirty",m.val()!==f._getNamesString(d,"id",","));f._refreshDirty()._getSaveBtn()});
		e&&m.select2("data",e);c.addClassName("transfered-to-select2");return f},setItem:function(a){this._item=a;return this},saveItem:function(a,c,d){var b,k;b=this;a&&(b._signRandID(a),jQuery("#"+a.id).prop("disabled",!0));b._disableAll($(b.getHTMLID("itemDiv")));b.postAjax(b.getCallbackId("saveItem"),c,{onSuccess:function(a,c){try{(k=b.getResp(c,!1,!0))&&k.item&&k.item.id&&(b._item=k.item,"function"===typeof d&&d(k),b.closeFancyBox())}catch(g){b.showModalBox('<strong class="text-danger">ERROR:</strong>',
		g),b._refreshDirty()._getSaveBtn()}},onComplete:function(){a&&jQuery("#"+a.id).prop("disabled",!1);b.refreshParentWindow()}});return b},_init:function(){return this},setPreData:function(a){a&&(this._preSetData=a);return this},bindAllEventNObjects:function(){return this},load:function(){this._init();$(this.getHTMLID("itemDiv")).addClassName("row");this._getInputDiv("name",this._item.name||"",$(this._containerIds.name),null,!0)._getInputDiv("description",this._item.description||"",$(this._containerIds.description))._getSaveBtn();
		return this},_getCommentsDiv:function(){var a,c;a=$(this._containerIds.comments);c=new Element("div");a.insert({bottom:this._getFormGroup("Comments",c,!0).addClassName("col-md-12")});this._signRandID(c);(new CommentsDivJs(this,this._focusEntity,this._item.id))._setDisplayDivId(c.id).render();return this}});