var PageJs=new Class.create;
PageJs.prototype=Object.extend(new DetailsPageJs,{load:function(){var a;a=this;a._init();$(a.getHTMLID("itemDiv")).addClassName("row");a._getInputDiv("name",a._item.name||"",$(a._containerIds.name),null,!0)._getInputDiv("description",a._item.description||"",$(a._containerIds.description))._getSelect2Div("Ingredient","ingredients",a._item.id?a._item.infos.ingredients:[],$(a._containerIds.ingredients),null)._getSaveBtn();a._addNewNutritionBtn($(a._containerIds.new_material_nutrition));a._item.infos.material_nutrition.each(function(c){a._addNutritionRow(c,
$(a._containerIds.material_nutrition))});a._fillDefautNutrition();return a},_fillDefautNutrition:function(){var a;a=this;jQuery.get("/ajax/getAll",{entityName:"DefaultNutrition"}).done(function(c){!0===c.succ&&c.resultData&&c.resultData.items&&Array.isArray(c.resultData.items)&&(c=c.resultData.items,c.each(function(b){!0!==a._checkNutritionExist(b.nutrition.id)&&a._addNutritionRow(b,$(a._containerIds.material_nutrition))}))});return a},_checkNutritionExist:function(a){var c,b,d;c=this;b=!1;$(c.getHTMLID("itemDiv")).getElementsBySelector(".material_nutrition[material_nutrition_id]").each(function(e){if(!0===
b)return b;(d=c._collectFormData($(e),"save-item"))&&d.nutrition&&parseInt(a)===parseInt(d.nutrition)&&(b=!0)});return b},_addNewNutritionBtn:function(a){var c,b,d,e;c=this;b=a||null;if(!b||!b.id)return c;d=(new Element("button",{"class":"newNutritionBtn btn btn-primary btn-sm"})).update("New Nutrition").observe("click",function(a){d.writeAttribute("disabled",!0);b.insert({bottom:e=new Element("div")});c._signRandID(e);c._addNutritionRow(null,e);d.writeAttribute("disabled",!1)});b.update(c._getFormGroup("",
d).addClassName("col-xs-12"));return c},_getNutritionRowDeleteBtn:function(a,c){var b,d,e,g,f,h;b=this;d=a||null;e=a?!0===a.active:!0;g=c||"";return f=(new Element("button",{"class":!0===e?"btn btn-sm btn-danger":"btn btn-sm btn-success"})).addClassName(g).insert({bottom:new Element("i",{"class":!0===e?"glyphicon glyphicon-trash":"glyphicon glyphicon-repeat"})}).observe("click",function(a){confirm("This "+(d?"":"newly added ")+"nutrition will be REMOVED, continue?")&&(h=f.up(".material_nutrition"),
d&&d.id&&h.up().insert({bottom:new Element("input",{type:"hidden","save-item":"ignore_"+d.id,dirty:!0})}),h.remove(),b._refreshDirty()._getSaveBtn())})},_addNutritionRow:function(a,c){var b,d,e,g,f;b=a||null;d=c||null;if(!d||!d.id)return this;d.insert({bottom:(new Element("div",{"class":"material_nutrition col-xs-12",material_nutrition_id:b?b.id:"new",active:b?b.active:!0})).insert({bottom:(new Element("div",{"class":"row "})).insert({bottom:d=new Element("div",{"class":"nutrition col-md-7 col-sm-4 col-xs-12"})}).insert({bottom:e=
new Element("div",{"class":"qty col-md-2 col-sm-3 col-xs-12"})}).insert({bottom:g=new Element("div",{"class":"servemeasurement col-md-2 col-sm-3  col-xs-12"})}).insert({bottom:(new Element("div",{"class":"pull-right text-right col-md-1 col-sm-1 col-xs-12"})).update(this._getNutritionRowDeleteBtn(b,"col-xs-12"))})})});this._getSelect2Div("Nutrition","nutrition",b?{id:b.nutrition.id,text:b.nutrition.name,data:b.nutrition}:null,d," ",!0,{multiple:!1,width:"100%",ajax:{delay:250,url:"/ajax/getAll",type:"GET",
data:function(a){return{searchTxt:"name like ?",searchParams:["%"+a+"%"],entityName:"Nutrition",pageNo:1}},results:function(a,b,c){f=[];a.resultData&&a.resultData.items&&a.resultData.items.each(function(a){f.push({id:a.id,text:a.name,data:a})});return{results:f}}},cache:!0,escapeMarkup:function(a){return a}})._getInputDiv("qty",b?b.qty:"",e," ",!0,"",!1,"Qty")._getSelect2Div("ServeMeasurement","serveMeasurement",b?{id:b.serveMeasurement.id,text:b.serveMeasurement.name,data:b.serveMeasurement}:null,
g," ",!0,{multiple:!1,width:"100%",ajax:{delay:250,url:"/ajax/getAll",type:"GET",data:function(a){return{searchTxt:"name like ?",searchParams:["%"+a+"%"],entityName:"ServeMeasurement",pageNo:1}},results:function(a,b,c){f=[];a.resultData&&a.resultData.items&&a.resultData.items.each(function(a){f.push({id:a.id,text:a.name,data:a})});return{results:f}}},cache:!0,escapeMarkup:function(a){return a}});return this},collectData:function(){var a,c,b;a=this;c=a._collectFormData($(a.getHTMLID("itemDiv")),"save-item");
if(!c)return null;c.material_nutrition=[];$(a.getHTMLID("itemDiv")).getElementsBySelector(".material_nutrition[material_nutrition_id]").each(function(d){(b=a._collectFormData($(d),"save-item"))&&c.material_nutrition.push(b)});return c}});