TRUNCATE TABLE `material`;
#materials
insert into `material`(`id`, `name`, `description`, `active`, `created`, `createdById`, `updated`, `updatedById`) values
(1, 'CALIFORNIA', 'Material of Product: CALIFORNIA', 1, NOW(), 10, NOW(), 10),
(2, 'TERIYAKI CHICKEN', 'Material of Product: TERIYAKI CHICKEN', 1, NOW(), 10, NOW(), 10),
(3, 'COOKED TUNA', 'Material of Product: COOKED TUNA', 1, NOW(), 10, NOW(), 10),
(4, 'SALMON AVOCADO', 'Material of Product: SALMON AVOCADO', 1, NOW(), 10, NOW(), 10),
(5, 'VEGETARIAN', 'Material of Product: VEGETARIAN', 1, NOW(), 10, NOW(), 10),
(6, 'COOKED PRAWN', 'Material of Product: COOKED PRAWN', 1, NOW(), 10, NOW(), 10),
(7, 'PRAWN TEMPURA', 'Material of Product: PRAWN TEMPURA', 1, NOW(), 10, NOW(), 10),
(8, 'KATSU CHICKEN', 'Material of Product: KATSU CHICKEN', 1, NOW(), 10, NOW(), 10),
(9, 'RICE HANDROLL', 'Material of Product: RICE HANDROLL', 1, NOW(), 10, NOW(), 10),
(13, 'CALIFORNIA (CUC)', 'Material of Product: CALIFORNIA (CUC)', 1, NOW(), 10, NOW(), 10),
(14, 'TERIYAKI CHICKEN (CUC)', 'Material of Product: TERIYAKI CHICKEN (CUC)', 1, NOW(), 10, NOW(), 10),
(15, 'COOKED TUNA (CUC)', 'Material of Product: COOKED TUNA (CUC)', 1, NOW(), 10, NOW(), 10),
(16, 'SALMON (CUC)', 'Material of Product: SALMON (CUC)', 1, NOW(), 10, NOW(), 10),
(17, 'COOKED PRAWN (CUC)', 'Material of Product: COOKED PRAWN (CUC)', 1, NOW(), 10, NOW(), 10),
(102, 'CALIFORNIA ', 'Material of Product: CALIFORNIA ', 1, NOW(), 10, NOW(), 10),
(103, 'TERIYAKI CHICKEN ', 'Material of Product: TERIYAKI CHICKEN ', 1, NOW(), 10, NOW(), 10),
(104, 'COOKED TUNA ', 'Material of Product: COOKED TUNA ', 1, NOW(), 10, NOW(), 10),
(105, 'SALMON AVOCADO ', 'Material of Product: SALMON AVOCADO ', 1, NOW(), 10, NOW(), 10),
(106, 'VEGETARIAN', 'Material of Product: VEGETARIAN', 1, NOW(), 10, NOW(), 10),
(107, 'COOKED PRAWN ', 'Material of Product: COOKED PRAWN ', 1, NOW(), 10, NOW(), 10),
(108, 'KATSU CHICKEN ', 'Material of Product: KATSU CHICKEN ', 1, NOW(), 10, NOW(), 10),
(109, 'SALMON SASHIMI 150g', 'Material of Product: SALMON SASHIMI 150g', 1, NOW(), 10, NOW(), 10),
(110, 'TUNA SASHIMI 150g', 'Material of Product: TUNA SASHIMI 150g', 1, NOW(), 10, NOW(), 10),
(111, 'KING FISH SASHIMI 150g', 'Material of Product: KING FISH SASHIMI 150g', 1, NOW(), 10, NOW(), 10),
(112, 'MIXED SASHIMI 150g', 'Material of Product: MIXED SASHIMI 150g', 1, NOW(), 10, NOW(), 10),
(113, 'SALMON NIGIRI ', 'Material of Product: SALMON NIGIRI ', 1, NOW(), 10, NOW(), 10),
(114, 'TUNA NIGIRI', 'Material of Product: TUNA NIGIRI', 1, NOW(), 10, NOW(), 10),
(115, 'PRAWN NIGIRI', 'Material of Product: PRAWN NIGIRI', 1, NOW(), 10, NOW(), 10),
(116, 'ABURI SALMON NIGIRI', 'Material of Product: ABURI SALMON NIGIRI', 1, NOW(), 10, NOW(), 10),
(117, 'NIGIRI COMBO', 'Material of Product: NIGIRI COMBO', 1, NOW(), 10, NOW(), 10),
(118, 'KING FISH NIGIRI', 'Material of Product: KING FISH NIGIRI', 1, NOW(), 10, NOW(), 10),
(119, 'RAINBOW ROLL', 'Material of Product: RAINBOW ROLL', 1, NOW(), 10, NOW(), 10),
(120, 'SALMON ONION ROLL', 'Material of Product: SALMON ONION ROLL', 1, NOW(), 10, NOW(), 10),
(121, 'TEMPURA PRAWN DRAGON', 'Material of Product: TEMPURA PRAWN DRAGON', 1, NOW(), 10, NOW(), 10),
(122, 'MANGO TEMPURA DRAGON', 'Material of Product: MANGO TEMPURA DRAGON', 1, NOW(), 10, NOW(), 10),
(123, 'SPIDER ROLL', 'Material of Product: SPIDER ROLL', 1, NOW(), 10, NOW(), 10),
(124, 'Dynamite Roll', 'Material of Product: Dynamite Roll', 1, NOW(), 10, NOW(), 10),
(125, 'CHILLI TUNA ROLL', 'Material of Product: CHILLI TUNA ROLL', 1, NOW(), 10, NOW(), 10),
(126, 'ORIGINAL CRUNCHY', 'Material of Product: ORIGINAL CRUNCHY', 1, NOW(), 10, NOW(), 10),
(127, 'KATSU CHICKEN CRUNCHY', 'Material of Product: KATSU CHICKEN CRUNCHY', 1, NOW(), 10, NOW(), 10),
(128, 'COOKED TUNA CRUNCHY', 'Material of Product: COOKED TUNA CRUNCHY', 1, NOW(), 10, NOW(), 10),
(129, 'TERIYAKI CHICKEN CRUNCHY', 'Material of Product: TERIYAKI CHICKEN CRUNCHY', 1, NOW(), 10, NOW(), 10),
(130, 'COOKED PRAWN CRUNCHY', 'Material of Product: COOKED PRAWN CRUNCHY', 1, NOW(), 10, NOW(), 10),
(131, 'AVOCADO HOSO', 'Material of Product: AVOCADO HOSO', 1, NOW(), 10, NOW(), 10),
(132, 'CUCUMBER HOSO', 'Material of Product: CUCUMBER HOSO', 1, NOW(), 10, NOW(), 10),
(133, 'COOKED TUNA HOSO', 'Material of Product: COOKED TUNA HOSO', 1, NOW(), 10, NOW(), 10),
(134, 'SALMON HOSO', 'Material of Product: SALMON HOSO', 1, NOW(), 10, NOW(), 10),
(135, 'RAW TUNA HOSO', 'Material of Product: RAW TUNA HOSO', 1, NOW(), 10, NOW(), 10),
(136, 'MIXED HOSO', 'Material of Product: MIXED HOSO', 1, NOW(), 10, NOW(), 10),
(137, 'TSUBAKI', 'Material of Product: TSUBAKI', 1, NOW(), 10, NOW(), 10),
(138, 'SAKURA', 'Material of Product: SAKURA', 1, NOW(), 10, NOW(), 10),
(139, 'UME', 'Material of Product: UME', 1, NOW(), 10, NOW(), 10),
(140, 'BOTAN', 'Material of Product: BOTAN', 1, NOW(), 10, NOW(), 10),
(141, 'SATSUKI', 'Material of Product: SATSUKI', 1, NOW(), 10, NOW(), 10),
(142, 'AKANE', 'Material of Product: AKANE', 1, NOW(), 10, NOW(), 10),
(143, 'KIKYO', 'Material of Product: KIKYO', 1, NOW(), 10, NOW(), 10),
(144, 'Quinoa Teriyaki Chicken', 'Material of Product: Quinoa Teriyaki Chicken', 1, NOW(), 10, NOW(), 10),
(145, 'Quinoa Cooked Tuna', 'Material of Product: Quinoa Cooked Tuna', 1, NOW(), 10, NOW(), 10),
(146, 'Quinoa Salmon', 'Material of Product: Quinoa Salmon', 1, NOW(), 10, NOW(), 10),
(147, 'Quinoa Katsu Chicken', 'Material of Product: Quinoa Katsu Chicken', 1, NOW(), 10, NOW(), 10),
(149, 'RAINBOW ROLL  (HALF)', 'Material of Product: RAINBOW ROLL  (HALF)', 1, NOW(), 10, NOW(), 10),
(150, 'SALMON ONION ROLL (HALF)', 'Material of Product: SALMON ONION ROLL (HALF)', 1, NOW(), 10, NOW(), 10),
(151, 'TEMP. PRAWN DRAGON (HALF)', 'Material of Product: TEMP. PRAWN DRAGON (HALF)', 1, NOW(), 10, NOW(), 10),
(152, 'MANGO TEMP. DRAGON (HALF)', 'Material of Product: MANGO TEMP. DRAGON (HALF)', 1, NOW(), 10, NOW(), 10),
(153, 'SPIDER ROLL (HALF)', 'Material of Product: SPIDER ROLL (HALF)', 1, NOW(), 10, NOW(), 10),
(154, 'CHILLI TUNA ROLL (HALF)', 'Material of Product: CHILLI TUNA ROLL (HALF)', 1, NOW(), 10, NOW(), 10),
(155, 'ORIGINAL CRUNCHY (HALF)', 'Material of Product: ORIGINAL CRUNCHY (HALF)', 1, NOW(), 10, NOW(), 10),
(156, 'KATSU CHICKEN CRUNCHY (HALF)', 'Material of Product: KATSU CHICKEN CRUNCHY (HALF)', 1, NOW(), 10, NOW(), 10),
(157, 'COOKED TUNA CRUNCHY (HALF)', 'Material of Product: COOKED TUNA CRUNCHY (HALF)', 1, NOW(), 10, NOW(), 10),
(158, 'TERIYAKI CHICKEN CRUNCHY (HALF)', 'Material of Product: TERIYAKI CHICKEN CRUNCHY (HALF)', 1, NOW(), 10, NOW(), 10),
(159, 'COOKED PRAWN CRUNCHY (HALF)', 'Material of Product: COOKED PRAWN CRUNCHY (HALF)', 1, NOW(), 10, NOW(), 10),
(160, 'TIGER ROLL CHICKEN HALF', 'Material of Product: TIGER ROLL CHICKEN HALF', 1, NOW(), 10, NOW(), 10),
(161, 'TIGER ROLL CHICKEN FULL', 'Material of Product: TIGER ROLL CHICKEN FULL', 1, NOW(), 10, NOW(), 10),
(162, 'TIGER ROLL TUNA HALF', 'Material of Product: TIGER ROLL TUNA HALF', 1, NOW(), 10, NOW(), 10),
(163, 'RIGER ROLL TUNA FULL', 'Material of Product: RIGER ROLL TUNA FULL', 1, NOW(), 10, NOW(), 10),
(165, '3 Plain Inari', 'Material of Product: 3 Plain Inari', 1, NOW(), 10, NOW(), 10),
(166, '2 Assorted Inari', 'Material of Product: 2 Assorted Inari', 1, NOW(), 10, NOW(), 10),
(204, 'PLATTER A', 'Material of Product: PLATTER A', 1, NOW(), 10, NOW(), 10),
(205, 'PLATTER B', 'Material of Product: PLATTER B', 1, NOW(), 10, NOW(), 10),
(206, 'PLATTER C', 'Material of Product: PLATTER C', 1, NOW(), 10, NOW(), 10),
(207, 'PLATTER D', 'Material of Product: PLATTER D', 1, NOW(), 10, NOW(), 10),
(208, 'CARNIVAL', 'Material of Product: CARNIVAL', 1, NOW(), 10, NOW(), 10),
(209, 'JUNBO', 'Material of Product: JUNBO', 1, NOW(), 10, NOW(), 10),
(304, 'SEAWEED SALAD', 'Material of Product: SEAWEED SALAD', 1, NOW(), 10, NOW(), 10),
(305, 'IKA SALAD', 'Material of Product: IKA SALAD', 1, NOW(), 10, NOW(), 10),
(306, 'mini chicken salad', 'Material of Product: mini chicken salad', 1, NOW(), 10, NOW(), 10),
(307, 'Baby Octopus Salad 130g', 'Material of Product: Baby Octopus Salad 130g', 1, NOW(), 10, NOW(), 10),
(308, 'Seafood Salad ', 'Material of Product: Seafood Salad ', 1, NOW(), 10, NOW(), 10),
(309, 'PRAWN GYOZA ', 'Material of Product: PRAWN GYOZA ', 1, NOW(), 10, NOW(), 10),
(310, 'VEGE GYOZA ', 'Material of Product: VEGE GYOZA ', 1, NOW(), 10, NOW(), 10),
(311, 'PORK GYOZA', 'Material of Product: PORK GYOZA', 1, NOW(), 10, NOW(), 10),
(313, 'PRAWN WRAP', 'Material of Product: PRAWN WRAP', 1, NOW(), 10, NOW(), 10),
(314, 'SMOKED SALMON WRAP', 'Material of Product: SMOKED SALMON WRAP', 1, NOW(), 10, NOW(), 10),
(315, 'VEGETABLE WRAP', 'Material of Product: VEGETABLE WRAP', 1, NOW(), 10, NOW(), 10),
(316, 'chicken Wrap', 'Material of Product: chicken Wrap', 1, NOW(), 10, NOW(), 10),
(319, 'Edamame', 'Material of Product: Edamame', 1, NOW(), 10, NOW(), 10),
(320, 'KARAGE CHICKEN', 'Material of Product: KARAGE CHICKEN', 1, NOW(), 10, NOW(), 10),
(321, 'YASAI KAKIAGE', 'Material of Product: YASAI KAKIAGE', 1, NOW(), 10, NOW(), 10),
(322, 'prawn tempura', 'Material of Product: prawn tempura', 1, NOW(), 10, NOW(), 10),
(323, 'VEGE TEMPURA', 'Material of Product: VEGE TEMPURA', 1, NOW(), 10, NOW(), 10),
(328, 'twin pack', 'Material of Product: twin pack', 1, NOW(), 10, NOW(), 10),
(329, 'three pack', 'Material of Product: three pack', 1, NOW(), 10, NOW(), 10),
(330, 'four pack', 'Material of Product: four pack', 1, NOW(), 10, NOW(), 10);
